version: '3.8'

x-ws-env: &ws_env
  WS_DEFAULT_URL: ${WS_DEFAULT_URL:-ws://feib.nl:5003}
x-cdn-env: &cdn_env
  CDN_BASE_URL: ${CDN_BASE_URL:-http://cdn.hitloop.feib.nl}

services:
  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    ports:
      - "5003:5000" # WebSocket server (bind on all interfaces)
    volumes:
      - ./socket-server:/app
    environment:
      - WS_HOST=0.0.0.0
      - WS_PORT=5000
      - PYTHONUNBUFFERED=1
      <<: *cdn_env
  client:
    build:
      context: ./socket-client
      dockerfile: Dockerfile
    ports:
      - "5004:5000" # Flask client UI
    volumes:
      - ./socket-client:/app
    environment:
      <<: [*ws_env, *cdn_env]
  cdn_server:
    build:
      context: ./cdn-server
      dockerfile: Dockerfile
    ports:
      - "5008:5000" # Flask CDN for static/firmware
    volumes:
      - ./cdn-server:/app
      - ./cdn-client/app/static/js:/app/static/js
      - ./cdn-client/app/static/firmware:/app/static/firmware
    environment:
      PYTHONUNBUFFERED: 1
      <<: *cdn_env
  device_control:
    build:
      context: ./device-control
      dockerfile: Dockerfile
    ports:
      - "5009:5000" # Flask device control UI
    volumes:
      - ./device-control:/app
    environment:
      <<: [*ws_env, *cdn_env]
      PYTHONUNBUFFERED: 1
  simulator:
    build:
      context: ./socket-simulator
      dockerfile: Dockerfile
    ports:
      - "5005:5000" # Flask simulator UI
    volumes:
      - ./socket-simulator:/app
    environment:
      <<: [*ws_env, *cdn_env]
  device_emulator:
    build:
      context: ./device-emulator
      dockerfile: Dockerfile
    ports:
      - "5007:5000" # Flask device emulator (mobile)
    volumes:
      - ./device-emulator:/app
    environment:
      <<: [*ws_env, *cdn_env]
  docs:
    build:
      context: ./documentation
      dockerfile: Dockerfile
    ports:
      - "5006:5000" # MkDocs documentation
    volumes:
      - ./documentation:/site
