version: '3.8'
services:
  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    ports:
      - "5003:5000" # WebSocket server (bind on all interfaces)
    volumes:
      - ./socket-server:/app
    environment:
      - WS_HOST=0.0.0.0
      - WS_PORT=5000
      - PYTHONUNBUFFERED=1
  client:
    build:
      context: ./socket-client
      dockerfile: Dockerfile
    ports:
      - "5004:5000" # Flask client UI
    volumes:
      - ./socket-client:/app
    environment:
      - WS_DEFAULT_URL=ws://localhost:5003/
  simulator:
    build:
      context: ./socket-simulator
      dockerfile: Dockerfile
    ports:
      - "5005:5000" # Flask simulator UI
    volumes:
      - ./socket-simulator:/app
    environment:
      - WS_DEFAULT_URL=ws://localhost:5003/
  device_emulator:
    build:
      context: ./device-emulator
      dockerfile: Dockerfile
    ports:
      - "5007:5000" # Flask device emulator (mobile)
    volumes:
      - ./device-emulator:/app
    environment:
      - WS_DEFAULT_URL=ws://localhost:5003/
  docs:
    build:
      context: ./documentation
      dockerfile: Dockerfile
    ports:
      - "5006:5000" # MkDocs documentation
    volumes:
      - ./documentation:/site
