version: '3.8'
services:
  grouploop-socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5003:5000" # WebSocket server
    volumes:
      - ./socket-server:/app
    environment:
      - WS_HOST=0.0.0.0
      - WS_PORT=5000
