version: '3.9'

services:
  socket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grouploop-socket
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - CORS_ORIGINS=*
      # - DEBUG=1
      # - SECRET_KEY=change-me
    restart: unless-stopped

