site_name: GroupLoop Documentation
site_url: http://docs.hitloop.feib.nl/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Services: architecture/services.md
    - Communication: architecture/communication.md
    - Data Flow: architecture/data-flow.md
  - Firmware:
    - Architecture: firmware/architecture.md
    - Processes: firmware/processes.md
    - Adding Processes: firmware/adding-process.md
    - Adding Commands: firmware/adding-commands.md
    - Configuration: firmware/configuration.md
  - Deployment:
    - Quick Start: deployment/quick-start.md
    - Configuration: deployment/configuration.md
    - New Host Setup: deployment/new-host.md
    - Firmware Upload: deployment/firmware-upload.md
  - Development:
    - Extending System: development/extending-system.md
    - Client Libraries: development/client-libraries.md
    - Testing: development/testing.md
  - Socket Demo:
    - Overview: socket-demo/index.md
    - Classes: socket-demo/classes.md
    - How-to: socket-demo/howto.md
  - Hardware:
    - Overview: hardware/hardware.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/grouploop
  version:
    provider: mike
