site_name: GroupLoop Docs
site_url: http://docs.hitloop.feib.nl/
theme:
  name: material
nav:
  - Home: index.md
  - Socket Demo:
    - Overview: socket-demo/index.md
    - Classes: socket-demo/classes.md
    - How-to: socket-demo/howto.md
plugins:
  - search
